name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "* $TITLE (#$NUMBER) @$AUTHOR"
categories:
  - title: "🚀 Features"
    when:
      labels:
        - "enhancement"
        - "feature"
  - title: "🐛 Bug Fixes"
    when:
      labels:
        - "bug"
        - "fix"
  - title: "📚 Documentation"
    when:
      labels:
        - "documentation"
  - title: "🔧 Maintenance"
    when:
      labels:
        - "dependencies"
        - "maintenance"
        - "chore"
  - type: "version-resolver"
    semver-increment: "major"
    when:
      label: "breaking"
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      label: "feature"
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      label: "enhancement"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      label: "bug"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      label: "documentation"
  - type: "version-resolver"
    semver-increment: "patch"
    when:
      label: "dependencies"
template: |
  ## Changes

  $CHANGES
